export const instruments = [
  "Electric Guitar",
  "Acoustic Guitar",
  "Bass",
  "Drums",
  "Percussion",
  "Vocals",
  "Keyboards",
  "Saxophone",
  "Trumpet",
  "Trombone",
];

export const venues = [
  {
    name: "United Center",
    location: {
      address: "1901 W Madison St",
      city: "Chicago",
      state: "IL",
      zipCode: "60612",
    },
  },
  {
    name: "Wrigley Field",
    location: {
      address: "1060 W Addison St",
      city: "Chicago",
      state: "IL",
      zipCode: "60613",
    },
  },
  {
    name: "Soldier Field",
    location: {
      address: "1410 Museum Campus Dr",
      city: "Chicago",
      state: "IL",
      zipCode: "60605",
    },
  },
  {
    name: "Chicago Theatre",
    location: {
      address: "175 N State St",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
  },
  {
    name: "Hollywood Casino Amphitheatre",
    location: {
      address: "19100 Ridgeland Ave",
      city: "Tinley Park",
      state: "IL",
      zipCode: "60477",
    },
  },
  {
    name: "Grant Park",
    location: {
      address: "337 E Randolph St",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
  },
  {
    name: "House of Blues Chicago",
    location: {
      address: "329 N Dearborn St",
      city: "Chicago",
      state: "IL",
      zipCode: "60654",
    },
  },
  {
    name: "Chicago Symphony Center",
    location: {
      address: "220 S Michigan Ave",
      city: "Chicago",
      state: "IL",
      zipCode: "60604",
    },
  },
  {
    name: "The Riviera Theatre",
    location: {
      address: "4746 N Racine Ave",
      city: "Chicago",
      state: "IL",
      zipCode: "60640",
    },
  },
  {
    name: "Metro Chicago",
    location: {
      address: "3730 N Clark St",
      city: "Chicago",
      state: "IL",
      zipCode: "60613",
    },
  },
];

export const musicians = [
  {
    name: "John Smith",
    instrument: "Electric Guitar",
    phoneNumber: "+1234567890",
    email: "john.smith@example.com",
  },
  {
    name: "Emma Johnson",
    instrument: "Electric Guitar",
    phoneNumber: "+1987654321",
    email: "emma.johnson@example.com",
  },
  {
    name: "David Lee",
    instrument: "Electric Guitar",
    phoneNumber: "+1122334455",
    email: "david.lee@example.com",
  },
  {
    name: "Sarah Clark",
    instrument: "Electric Guitar",
    phoneNumber: "+1555666777",
    email: "sarah.clark@example.com",
  },
  {
    name: "Michael Thompson",
    instrument: "Electric Guitar",
    phoneNumber: "+1444333222",
    email: "michael.thompson@example.com",
  },
  {
    name: "Robert Garcia",
    instrument: "Acoustic Guitar",
    phoneNumber: "+1789456123",
    email: "robert.garcia@example.com",
  },
  {
    name: "Laura Martinez",
    instrument: "Acoustic Guitar",
    phoneNumber: "+1666777888",
    email: "laura.martinez@example.com",
  },
  {
    name: "Chris Brown",
    instrument: "Acoustic Guitar",
    phoneNumber: "+1888999000",
    email: "chris.brown@example.com",
  },
  {
    name: "Maria Rodriguez",
    instrument: "Acoustic Guitar",
    phoneNumber: "+1999888777",
    email: "maria.rodriguez@example.com",
  },
  {
    name: "Daniel Wilson",
    instrument: "Acoustic Guitar",
    phoneNumber: "+1222111333",
    email: "daniel.wilson@example.com",
  },
  {
    name: "Alex Turner",
    instrument: "Bass",
    phoneNumber: "+1555123456",
    email: "alex.turner@example.com",
  },
  {
    name: "Olivia White",
    instrument: "Bass",
    phoneNumber: "+1444555666",
    email: "olivia.white@example.com",
  },
  {
    name: "James Brown",
    instrument: "Bass",
    phoneNumber: "+1666888999",
    email: "james.brown@example.com",
  },
  {
    name: "Sofia Martinez",
    instrument: "Bass",
    phoneNumber: "+1777999888",
    email: "sofia.martinez@example.com",
  },
  {
    name: "Benjamin Davis",
    instrument: "Bass",
    phoneNumber: "+1888222333",
    email: "benjamin.davis@example.com",
  },
  {
    name: "William Harris",
    instrument: "Drums",
    phoneNumber: "+1999777666",
    email: "william.harris@example.com",
  },
  {
    name: "Isabella Taylor",
    instrument: "Drums",
    phoneNumber: "+1222333444",
    email: "isabella.taylor@example.com",
  },
  {
    name: "Ethan Martin",
    instrument: "Drums",
    phoneNumber: "+1333444555",
    email: "ethan.martin@example.com",
  },
  {
    name: "Mia Anderson",
    instrument: "Drums",
    phoneNumber: "+1444666777",
    email: "mia.anderson@example.com",
  },
  {
    name: "Mason Moore",
    instrument: "Drums",
    phoneNumber: "+1555777888",
    email: "mason.moore@example.com",
  },
  {
    name: "Sophia Lee",
    instrument: "Percussion",
    phoneNumber: "+1666999888",
    email: "sophia.lee@example.com",
  },
  {
    name: "Ryan Wilson",
    instrument: "Percussion",
    phoneNumber: "+1555444333",
    email: "ryan.wilson@example.com",
  },
  {
    name: "Ella Thompson",
    instrument: "Percussion",
    phoneNumber: "+1222333777",
    email: "ella.thompson@example.com",
  },
  {
    name: "Noah Davis",
    instrument: "Percussion",
    phoneNumber: "+1333222777",
    email: "noah.davis@example.com",
  },
  {
    name: "Ava Hernandez",
    instrument: "Percussion",
    phoneNumber: "+1777333222",
    email: "ava.hernandez@example.com",
  },
  {
    name: "Lucas Rodriguez",
    instrument: "Vocals",
    phoneNumber: "+1444222333",
    email: "lucas.rodriguez@example.com",
  },
  {
    name: "Chloe Martinez",
    instrument: "Vocals",
    phoneNumber: "+1666555444",
    email: "chloe.martinez@example.com",
  },
  {
    name: "Jackson Lee",
    instrument: "Vocals",
    phoneNumber: "+1555333666",
    email: "jackson.lee@example.com",
  },
  {
    name: "Avery Taylor",
    instrument: "Vocals",
    phoneNumber: "+1222888999",
    email: "avery.taylor@example.com",
  },
  {
    name: "Sophie Brown",
    instrument: "Vocals",
    phoneNumber: "+1888777666",
    email: "sophie.brown@example.com",
  },
  {
    name: "Ethan Turner",
    instrument: "Keyboards",
    phoneNumber: "+1222999888",
    email: "ethan.turner@example.com",
  },
  {
    name: "Ava Wilson",
    instrument: "Keyboards",
    phoneNumber: "+1444999777",
    email: "ava.wilson@example.com",
  },
  {
    name: "Lucas Brown",
    instrument: "Keyboards",
    phoneNumber: "+1666777666",
    email: "lucas.brown@example.com",
  },
  {
    name: "Chloe Garcia",
    instrument: "Keyboards",
    phoneNumber: "+1888666555",
    email: "chloe.garcia@example.com",
  },
  {
    name: "Mia Martinez",
    instrument: "Keyboards",
    phoneNumber: "+1999555444",
    email: "mia.martinez@example.com",
  },
  {
    name: "Daniel Hernandez",
    instrument: "Saxophone",
    phoneNumber: "+1666888999",
    email: "daniel.hernandez@example.com",
  },
  {
    name: "Emma Johnson",
    instrument: "Saxophone",
    phoneNumber: "+1444555666",
    email: "emma.johnson2@example.com",
  },
  {
    name: "Olivia White",
    instrument: "Saxophone",
    phoneNumber: "+1222111333",
    email: "olivia.white2@example.com",
  },
  {
    name: "William Harris",
    instrument: "Saxophone",
    phoneNumber: "+1999777666",
    email: "william.harris2@example.com",
  },
  {
    name: "Benjamin Davis",
    instrument: "Saxophone",
    phoneNumber: "+1555666777",
    email: "benjamin.davis2@example.com",
  },
  {
    name: "Sophia Garcia",
    instrument: "Trumpet",
    phoneNumber: "+1222333444",
    email: "sophia.garcia@example.com",
  },
  {
    name: "Ryan Brown",
    instrument: "Trumpet",
    phoneNumber: "+1999888777",
    email: "ryan.brown@example.com",
  },
  {
    name: "Ella Davis",
    instrument: "Trumpet",
    phoneNumber: "+1666777888",
    email: "ella.davis@example.com",
  },
  {
    name: "Noah Rodriguez",
    instrument: "Trumpet",
    phoneNumber: "+1555444333",
    email: "noah.rodriguez@example.com",
  },
  {
    name: "Ava Thompson",
    instrument: "Trumpet",
    phoneNumber: "+1444333222",
    email: "ava.thompson@example.com",
  },
  {
    name: "Lucas Hernandez",
    instrument: "Trombone",
    phoneNumber: "+1666555444",
    email: "lucas.hernandez@example.com",
  },
  {
    name: "Chloe Taylor",
    instrument: "Trombone",
    phoneNumber: "+1555333666",
    email: "chloe.taylor@example.com",
  },
  {
    name: "Jackson Moore",
    instrument: "Trombone",
    phoneNumber: "+1888999000",
    email: "jackson.moore@example.com",
  },
  {
    name: "Avery Lee",
    instrument: "Trombone",
    phoneNumber: "+1777999888",
    email: "avery.lee@example.com",
  },
  {
    name: "Sophie Martin",
    instrument: "Trombone",
    phoneNumber: "+1789456123",
    email: "sophie.martin@example.com",
  },
];

export const gigs = [
  {
    name: "Rock Fusion Jam",
    startTime: "2024-10-10T10:00:00Z",
    endTime: "2024-10-10T13:00:00Z",
    venue: "United Center",
    musicians: [
      { name: "John Smith", inst: "Electric Guitar" },
      { name: "Robert Garcia", inst: "Acoustic Guitar" },
      { name: "Alex Turner", inst: "Bass" },
      { name: "William Harris", inst: "Drums" },
      { name: "Sophia Lee", inst: "Saxophone" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Saxophone"],
  },
  {
    name: "Acoustic Serenade",
    startTime: "2024-10-11T15:00:00Z",
    endTime: "2024-10-11T18:00:00Z",
    venue: "Wrigley Field",
    musicians: [
      { name: "Emma Johnson", inst: "Electric Guitar" },
      { name: "Laura Martinez", inst: "Acoustic Guitar" },
      { name: "Olivia White", inst: "Bass" },
      { name: "Isabella Taylor", inst: "Drums" },
      { name: "Ryan Brown", inst: "Trumpet" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Trumpet"],
  },
  {
    name: "Blues Rendezvous",
    startTime: "2024-10-12T19:00:00Z",
    endTime: "2024-10-12T22:00:00Z",
    venue: "Soldier Field",
    musicians: [
      { name: "David Lee", inst: "Electric Guitar" },
      { name: "Chris Brown", inst: "Acoustic Guitar" },
      { name: "James Brown", inst: "Bass" },
      { name: "Ethan Martin", inst: "Drums" },
      { name: "Ella Thompson", inst: "Percussion" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Percussion"],
  },
  {
    name: "Jazz Night Out",
    startTime: "2024-10-13T20:00:00Z",
    endTime: "2024-10-13T23:00:00Z",
    venue: "Chicago Theatre",
    musicians: [
      { name: "Sarah Clark", inst: "Electric Guitar" },
      { name: "Maria Rodriguez", inst: "Acoustic Guitar" },
      { name: "Benjamin Davis", inst: "Bass" },
      { name: "Mia Anderson", inst: "Drums" },
      { name: "Noah Davis", inst: "Vocals" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Vocals"],
  },
  {
    name: "Pop Extravaganza",
    startTime: "2024-10-14T18:00:00Z",
    endTime: "2024-10-14T21:00:00Z",
    venue: "Hollywood Casino Amphitheatre",
    musicians: [
      { name: "Michael Thompson", inst: "Electric Guitar" },
      { name: "Daniel Wilson", inst: "Acoustic Guitar" },
      { name: "Sofia Martinez", inst: "Bass" },
      { name: "Mason Moore", inst: "Drums" },
      { name: "Ava Hernandez", inst: "Keyboards" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Keyboards"],
  },
  {
    name: "Funk Fusion Fest",
    startTime: "2024-10-15T16:00:00Z",
    endTime: "2024-10-15T19:00:00Z",
    venue: "Grant Park",
    musicians: [
      { name: "Emma Johnson", inst: "Electric Guitar" },
      { name: "Daniel Wilson", inst: "Acoustic Guitar" },
      { name: "Lucas Rodriguez", inst: "Bass" },
      { name: "Sophie Martin", inst: "Drums" },
      { name: "Chloe Taylor", inst: "Trombone" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Trombone"],
  },
  {
    name: "Indie Showcase",
    startTime: "2024-10-16T14:00:00Z",
    endTime: "2024-10-16T17:00:00Z",
    venue: "House of Blues Chicago",
    musicians: [
      { name: "Olivia White", inst: "Electric Guitar" },
      { name: "Chris Brown", inst: "Acoustic Guitar" },
      { name: "Chloe Martinez", inst: "Bass" },
      { name: "Jackson Lee", inst: "Drums" },
      { name: "Avery Taylor", inst: "Vocals" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Vocals"],
  },
  {
    name: "Soulful Soiree",
    startTime: "2024-10-17T20:00:00Z",
    endTime: "2024-10-17T23:00:00Z",
    venue: "Chicago Symphony Center",
    musicians: [
      { name: "Sophia Garcia", inst: "Electric Guitar" },
      { name: "Ryan Brown", inst: "Acoustic Guitar" },
      { name: "Ella Davis", inst: "Bass" },
      { name: "Noah Rodriguez", inst: "Drums" },
      { name: "Ava Thompson", inst: "Trumpet" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Trumpet"],
  },
  {
    name: "Latin Fusion Fiesta",
    startTime: "2024-10-18T19:00:00Z",
    endTime: "2024-10-18T22:00:00Z",
    venue: "The Riviera Theatre",
    musicians: [
      { name: "Lucas Hernandez", inst: "Electric Guitar" },
      { name: "Jackson Moore", inst: "Acoustic Guitar" },
      { name: "Avery Lee", inst: "Bass" },
      { name: "Sophie Martin", inst: "Drums" },
      { name: "Chloe Garcia", inst: "Trombone" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Trombone"],
  },
  {
    name: "Reggae Revolution",
    startTime: "2024-10-19T18:00:00Z",
    endTime: "2024-10-19T21:00:00Z",
    venue: "Metro Chicago",
    musicians: [
      { name: "John Smith", inst: "Electric Guitar" },
      { name: "Emma Johnson", inst: "Acoustic Guitar" },
      { name: "Sophia Lee", inst: "Bass" },
      { name: "Ethan Turner", inst: "Drums" },
      { name: "Ava Wilson", inst: "Keyboards" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Keyboards"],
  },
  {
    name: "Country Chillout",
    startTime: "2024-10-20T17:00:00Z",
    endTime: "2024-10-20T20:00:00Z",
    venue: "Hollywood Casino Amphitheatre",
    musicians: [
      { name: "David Lee", inst: "Electric Guitar" },
      { name: "Robert Garcia", inst: "Acoustic Guitar" },
      { name: "Alex Turner", inst: "Bass" },
      { name: "Isabella Taylor", inst: "Drums" },
      { name: "Ella Thompson", inst: "Vocals" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Vocals"],
  },
  {
    name: "R&B Groove",
    startTime: "2024-10-21T20:00:00Z",
    endTime: "2024-10-21T23:00:00Z",
    venue: "Chicago Symphony Center",
    musicians: [
      { name: "Sarah Clark", inst: "Electric Guitar" },
      { name: "Laura Martinez", inst: "Acoustic Guitar" },
      { name: "James Brown", inst: "Bass" },
      { name: "Mia Anderson", inst: "Drums" },
      { name: "Sophia Garcia", inst: "Percussion" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Percussion"],
  },
  {
    name: "Classical Elegance",
    startTime: "2024-10-22T19:00:00Z",
    endTime: "2024-10-22T22:00:00Z",
    venue: "The Riviera Theatre",
    musicians: [
      { name: "Michael Thompson", inst: "Electric Guitar" },
      { name: "Maria Rodriguez", inst: "Acoustic Guitar" },
      { name: "Sofia Martinez", inst: "Bass" },
      { name: "Mason Moore", inst: "Drums" },
      { name: "Chloe Garcia", inst: "Keyboards" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Keyboards"],
  },
  {
    name: "Electronic Beats",
    startTime: "2024-10-23T18:00:00Z",
    endTime: "2024-10-23T21:00:00Z",
    venue: "Grant Park",
    musicians: [
      { name: "William Harris", inst: "Electric Guitar" },
      { name: "Daniel Wilson", inst: "Acoustic Guitar" },
      { name: "Ethan Martin", inst: "Bass" },
      { name: "Noah Davis", inst: "Drums" },
      { name: "Ava Thompson", inst: "Keyboards" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Keyboards"],
  },
  {
    name: "Hip Hop Showdown",
    startTime: "2024-10-24T17:00:00Z",
    endTime: "2024-10-24T20:00:00Z",
    venue: "House of Blues Chicago",
    musicians: [
      { name: "John Smith", inst: "Electric Guitar" },
      { name: "Emma Johnson", inst: "Acoustic Guitar" },
      { name: "David Lee", inst: "Bass" },
      { name: "Laura Martinez", inst: "Drums" },
      { name: "Olivia White", inst: "Vocals" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Vocals"],
  },
  {
    name: "Metal Mayhem",
    startTime: "2024-10-25T20:00:00Z",
    endTime: "2024-10-25T23:00:00Z",
    venue: "Metro Chicago",
    musicians: [
      { name: "Robert Garcia", inst: "Electric Guitar" },
      { name: "Chris Brown", inst: "Acoustic Guitar" },
      { name: "Sarah Clark", inst: "Bass" },
      { name: "Michael Thompson", inst: "Drums" },
      { name: "Sophia Lee", inst: "Saxophone" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Saxophone"],
  },
  {
    name: "World Music Gala",
    startTime: "2024-10-26T19:00:00Z",
    endTime: "2024-10-26T22:00:00Z",
    venue: "Chicago Theatre",
    musicians: [
      { name: "William Harris", inst: "Electric Guitar" },
      { name: "Maria Rodriguez", inst: "Acoustic Guitar" },
      { name: "James Brown", inst: "Bass" },
      { name: "Mia Anderson", inst: "Drums" },
      { name: "Ethan Turner", inst: "Keyboards" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Keyboards"],
  },
  {
    name: "Experimental Soundscape",
    startTime: "2024-10-27T18:00:00Z",
    endTime: "2024-10-27T21:00:00Z",
    venue: "House of Blues Chicago",
    musicians: [
      { name: "Alex Turner", inst: "Electric Guitar" },
      { name: "Laura Martinez", inst: "Acoustic Guitar" },
      { name: "Ella Thompson", inst: "Bass" },
      { name: "Sophie Martin", inst: "Drums" },
      { name: "Chloe Taylor", inst: "Trombone" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Trombone"],
  },
  {
    name: "Gospel Gathering",
    startTime: "2024-10-28T17:00:00Z",
    endTime: "2024-10-28T20:00:00Z",
    venue: "Chicago Symphony Center",
    musicians: [
      { name: "Emma Johnson", inst: "Electric Guitar" },
      { name: "Chris Brown", inst: "Acoustic Guitar" },
      { name: "Ryan Brown", inst: "Bass" },
      { name: "Sophia Garcia", inst: "Drums" },
      { name: "Noah Davis", inst: "Vocals" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Vocals"],
  },
  {
    name: "Symphonic Spectacle",
    startTime: "2024-10-29T20:00:00Z",
    endTime: "2024-10-29T23:00:00Z",
    venue: "Metro Chicago",
    musicians: [
      { name: "John Smith", inst: "Electric Guitar" },
      { name: "Robert Garcia", inst: "Acoustic Guitar" },
      { name: "Sarah Clark", inst: "Bass" },
      { name: "Michael Thompson", inst: "Drums" },
      { name: "Sophia Lee", inst: "Saxophone" },
    ],
    instrumentation: ["Electric Guitar", "Acoustic Guitar", "Bass", "Drums", "Saxophone"],
  },
];

