import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { api } from "~/trpc/server";
import { TRPCReactProvider } from "~/trpc/react";
import StoreProvider from "./StoreProvider";
import { defaultGigForm } from "~/api/gig";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

const allInstruments = await api.instrument.getAll();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
      <StoreProvider instruments={allInstruments ? allInstruments : []} gigForm={defaultGigForm}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
